import { Injectable } from '@angular/core';
import { AngularFireAuth } from '@angular/fire/compat/auth';
import { AngularFirestore } from '@angular/fire/compat/firestore';
import { AngularFireStorage } from '@angular/fire/compat/storage';
import { Router } from '@angular/router';
import { Observable, combineLatest, from } from 'rxjs';
import { map, switchMap } from 'rxjs/operators';
import { ProfilePic } from '../_models/profilePic.model';

@Injectable({
    providedIn: 'root'
})
export class AuthService {

    userLoggedIn: boolean;      // other components can check on this variable for the login status of the user

    constructor(private router: Router, private afAuth: AngularFireAuth, private afs: AngularFirestore, private storage: AngularFireStorage,
    ) {
        this.userLoggedIn = false;

        this.afAuth.onAuthStateChanged((user) => {              // set up a subscription to always know the login status of the user
            if (user) {
                this.userLoggedIn = true;
            } else {
                this.userLoggedIn = false;
            }
        });
    }

    getAuthState(): Observable<any> {
        return this.afAuth.authState;
    }

    isUserLoggedIn(): Observable<boolean> {
        return this.afAuth.authState.pipe(map(user => !!user));
    }

    loginUser(email: string, password: string): Promise<any> {
        return this.afAuth.signInWithEmailAndPassword(email, password)
            .then(() => {
                console.log('Auth Service: loginUser: success');
                this.router.navigate(['/profile-dashboard'])
            })
            .catch(error => {
                console.log('Auth Service: login error...');
                console.log('error code', error.code);
                console.log('error', error);
                if (error.code)
                    return { isValid: false, message: error.message };
            });
    }

    signupUser(user: any): Promise<any> {
        return this.afAuth.createUserWithEmailAndPassword(user.email, user.password)
            .then((result) => {
                let emailLower = user.email.toLowerCase();
                const uid = result.user.uid; // Get the User UID generated by Firebase

                this.afs.doc('/users/' + emailLower) // Use the email as the document ID
                    .set({
                        accountType: 'endUser',
                        isPaying: true,
                        owner: user.owner,
                        location_name: user.location_name,
                        description: user.description,
                        email: user.email,
                        phone: user.phone,
                        website: user.website,
                        address: user.address,
                        zip: user.zip,
                        school: user.school,
                        pin: user.pin,
                        email_lower: emailLower,
                        textsThisMonth: 0,
                        uid: uid
                    });

                result.user.sendEmailVerification(); // Immediately send the user a verification email
            })
            .catch(error => {
                console.log('Auth Service: signup error', error);
                if (error.code)
                    return { isValid: false, message: error.message };
            });
    }


    resetPassword(email: string): Promise<any> {
        return this.afAuth.sendPasswordResetEmail(email)
            .then(() => {
                console.log('Auth Service: reset password success');
                // this.router.navigate(['/amount']);
            })
            .catch(error => {
                console.log('Auth Service: reset password error...');
                console.log(error.code);
                console.log(error)
                if (error.code)
                    return error;
            });
    }

    async resendVerificationEmail() {                         // verification email is sent in the Sign Up function, but if you need to resend, call this function
        return (await this.afAuth.currentUser).sendEmailVerification()
            .then(() => {
                // this.router.navigate(['login']);
            })
            .catch(error => {
                console.log('Auth Service: sendVerificationEmail error...');
                console.log('error code', error.code);
                console.log('error', error);
                if (error.code)
                    return error;
            });
    }

    logoutUser(): Promise<void> {
        return this.afAuth.signOut()
            .then(() => {
                this.router.navigate(['/login']);                    // when we log the user out, navigate them to home
            })
            .catch(error => {
                console.log('Auth Service: logout error...');
                console.log('error code', error.code);
                console.log('error', error);
                if (error.code)
                    return error;
            });
    }

    getCurrentUser() {
        return this.afAuth.currentUser;                                 // returns user object for logged-in users, otherwise returns null 
    }

    getCurrentUserInfo(email) {
        return this.afs
            .collection("users")
            .doc(email)
            .valueChanges();
    }

    updateUser(email: string, user: any): Promise<void> {
        // ensure email is lower case since that's what we use in our Firestore document paths
        const emailLower = email.toLowerCase();

        // merge the new user data with the existing data
        // this way, only provided fields will be updated
        return this.afs.doc('/users/' + emailLower).update(user)
            .then(() => {
                console.log('Auth Service: updateUser: success');
            })
            .catch(error => {
                console.log('Auth Service: updateUser: error...');
                console.log('error code', error.code);
                console.log('error', error);
                if (error.code)
                    return error;
            });
    }

    updateTextsThisMonth(totalMessagesCount: number): Promise<void> {
        return this.afAuth.currentUser
            .then((user) => {
                if (!user || !user.email) {
                    throw new Error("User is not logged in.");
                }

                const emailLower = user.email.toLowerCase();

                return this.afs
                    .doc(`/users/${emailLower}`)
                    .get()
                    .toPromise()
                    .then((doc) => {
                        const userData = doc.data() as { textsThisMonth?: number };

                        if (!userData || userData.textsThisMonth === undefined) {
                            throw new Error("User data not found.");
                        }

                        const currentTextsThisMonth = userData.textsThisMonth || 0;
                        const newTextsThisMonth = currentTextsThisMonth + totalMessagesCount;

                        return this.afs
                            .doc(`/users/${emailLower}`)
                            .update({ textsThisMonth: newTextsThisMonth });
                    });
            })
            .catch((error) => {
                console.log("Auth Service: updateTextsThisMonth: error...");
                console.log("error code", error.code);
                console.log("error", error);
                throw error;
            });
    }

    // In AuthService
    getImageCount(userId: string): Observable<number> {
        // Query the storage and get the images
        let images = from(this.storage.ref('profilePictures/' + userId).listAll());

        return images.pipe(map(imagesResult => {
            return imagesResult.items.length;
        }));
    }

    addImageRecord(userId: string, imageUrl: string) {
        return this.afs.collection('profilePics').add({
            uid: userId,
            imageUrl: imageUrl
        });
    }

    deleteImageRecord(userId: string, imageUrl: string) {
        return this.afs.collection('profilePics', ref => ref.where('uid', '==', userId).where('imageUrl', '==', imageUrl))
            .get().toPromise()
            .then(snapshot => {
                snapshot.forEach(doc => {
                    doc.ref.delete();
                });
            });
    }

    getImageUrls(userId: string): Observable<string[]> {
        return this.afs.collection<ProfilePic>('profilePics', ref => ref.where('uid', '==', userId))
            .valueChanges()
            .pipe(map(docs => docs.map(doc => doc.imageUrl)));
    }
}
