# firebase-hosting-merge.yml
name: Deploy to Firebase Hosting on merge

'on':
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm ci

      - name: Semantic Release
        id: semantic
        run: |
          OUTPUT=$(npx semantic-release)
          echo "Release output: $OUTPUT"
          VERSION=$(echo "$OUTPUT" | grep "The next release version is" | cut -d " " -f 6)
          if [ -n "$VERSION" ]; then
            echo "::set-output name=version::$VERSION"
          else
            echo "No new release version detected."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update environment files with new version
        if: steps.semantic.outputs.version
        run: node ./scripts/version-replacer.js ${{ steps.semantic.outputs.version }}

      - run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SERVING_U_APP_5D02D }}
          channelId: live
          projectId: servinguapp-5d02d
