# release.yml
name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run semantic-release
        id: semantic
        run: |
          OUTPUT=$(npx semantic-release)
          echo "Release output: $OUTPUT"
          VERSION=$(echo "$OUTPUT" | grep "The next release version is" | cut -d " " -f 6)
          if [ -n "$VERSION" ]; then
            echo "::set-output name=version::$VERSION"
          else
            echo "No new release version detected."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update environment files with new version
        if: steps.semantic.outputs.version
        run: node ./scripts/version-replacer.js ${{ steps.semantic.outputs.version }}
